---

- name: Add repository
  hosts: app_server
  become: yes
  tasks:
    - yum_repository:
        name: epel
        description: EPEL YUM repo
        baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      when: (not {{ DEV }}) or
            ({{ FORCE_UPDATE }})

- name: Install Python3
  hosts: app_server
  tasks:
    - yum:
        name:
          - python3
          - python3-pip
          - python3-setuptools
          - git
        state: present
      when: (not {{ DEV }}) or
            ({{ FORCE_UPDATE }})

- name: create pip directory
  hosts: app_server
  tasks:
    - file: >-
        path=/root/.pip
        state=directory
        mode=0755

- name: configure pip
  hosts: app_server
  tasks:
    - template: >-
        src=pip.conf
        dest=/root/.pip/pip.conf
        mode=0644
      when: (not {{ DEV }}) or
            ({{ FORCE_UPDATE }})

- name: Download App from repo
  hosts: app_server
  tasks:
    - git:
        repo: 'https://github.com/BrainGu-Tim/test.git'
        dest: /my_app
      when: (not {{ DEV }}) or
            ({{ FORCE_UPDATE }})

- name: Install pip requirements
  hosts: app_server
  tasks:
    - pip:
        virtualenv: /my_app/venv
        #virtualenv_command: /usr/bin/python3 -m venv
        #executable: pip3
        virtual_python: python3
        requirements: /my_app/requirements.txt
      when: (not {{ DEV }}) or
            ({{ FORCE_UPDATE }})

