---

- name: Add repository
  hosts: app_server
  tasks:
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
    when: (not {{ DEV }}) or
          ({{ FORCE_UPDATE }})

- name: Install Python3 and pip
  hosts: app_server
  tasks:
    yum:
      name:
        - python3
        - python3-pip
      state: present
    when: (not {{ DEV }}) or
          ({{ FORCE_UPDATE }})

- name: create pip directory
  hosts: app_server
  tasks:
    file: >-
      path=/root/.pip
      state=directory
      mode=0755

- name: configure pip
  hosts: app_server
  tasks:
    template: >-
      src=pip.conf
      dest=/root/.pip/pip.conf
      mode=0644
    when: (not {{ DEV }}) or
          ({{ FORCE_UPDATE }})

- name: Download App from repo
  hosts: app_server
  tasks:
    git:
      repo: 'https://foosball.example.org/path/to/repo.git'
      dest: /my_app
    when: (not {{ DEV }}) or
          ({{ FORCE_UPDATE }})

