---

- name: Add repository
  yum_repository:
    name: epel
    description: EPEL YUM repo
    baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
  when: (not {{ DEV }}) or
        ({{ FORCE_UPDATE }})

- name: Install Python 3 and pip
  yum:
    name:
      - python3
      - python3-pip
    state: present
  when: (not {{ DEV }}) or
        ({{ FORCE_UPDATE }})

- name: create pip directory
  file: >-
    path=/root/.pip
    state=directory
    mode=0755

- name: configure pip
  template: >-
    src=pip.conf
    dest=/root/.pip/pip.conf
    mode=0644
  when: (not {{ DEV }}) or
        ({{ FORCE_UPDATE }})

- name: Download App from repo
  git:
    repo: 'https://github.com/BrainGu-Tim/test.git'
    dest: /my_app
  when: (not {{ DEV }}) or
        ({{ FORCE_UPDATE }})

#- name: Install pip requirements
#  pip:
#    requirements: /my_app/requirements.txt
#    virtualenv: /my_app/venv

